# Generated by Django 3.2.8 on 2021-10-31 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=40)),
                ('authorization', models.CharField(blank=True, max_length=191, null=True)),
                ('app_url_android', models.URLField(blank=True, null=True)),
                ('autosubtitles', models.BooleanField(default=False)),
                ('show_streaming', models.BooleanField(default=False)),
                ('show_ads_in_player', models.BooleanField(default=False)),
                ('show_anime', models.BooleanField(default=False)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('latest_version', models.CharField(blank=True, max_length=4, null=True)),
                ('update_title', models.CharField(max_length=40)),
                ('release_note', models.TextField(blank=True, null=True)),
                ('enable_custom_message', models.BooleanField(default=False)),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('tmdb_cover_path', models.URLField(default='http://image.tmdb.org/t/p/w500')),
                ('featured_home_numbers', models.IntegerField(default=5)),
                ('next_episode_timer', models.PositiveSmallIntegerField(default=10)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('media_placehoder_path', models.CharField(blank=True, max_length=100, null=True)),
                ('server_choices', models.BooleanField(default=False)),
                ('download_premium_only', models.BooleanField(default=False)),
                ('wach_ads_to_unlock_player', models.BooleanField(default=False)),
                ('enable_custom_banner', models.BooleanField(default=False)),
                ('custom_banner_image', models.ImageField(blank=True, null=True, upload_to='custom_banner')),
                ('custom_banner_link', models.URLField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_external_player_to_download', models.BooleanField(default=False)),
                ('default_youtube_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('enable_previews', models.BooleanField(default=False)),
                ('enable_pinned', models.BooleanField(default=False)),
                ('enable_vlc', models.BooleanField(default=False)),
                ('resume_offline', models.BooleanField(default=True)),
                ('user_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('enable_upcoming', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
