# Generated by Django 3.2.8 on 2021-10-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='mantenance_mode_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='splash_image',
            field=models.ImageField(blank=True, null=True, upload_to='splash'),
        ),
    ]
