# Generated by Django 3.2.8 on 2021-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0002_auto_20211031_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'verbose_name_plural': 'Android Configuration'},
        ),
        migrations.AddField(
            model_name='configuration',
            name='default_downloads_options',
            field=models.CharField(choices=[('Free', 'Free'), ('WithAdsUnlock', 'WithAdsUnlock'), ('PremiumOnly', 'PremiumOnly')], default='Free', max_length=13),
        ),
    ]
