# Generated by Django 3.2.8 on 2021-10-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_auto_20211031_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='authorization',
            new_name='firebase_server_key',
        ),
    ]
