# Generated by Django 3.2.8 on 2021-10-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_rename_authorization_configuration_firebase_server_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='update_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
