# Generated by Django 3.2.8 on 2021-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_alter_configuration_update_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='show_ads_in_player',
            new_name='ads_player',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='show_anime',
            new_name='anime',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='firebase_server_key',
            new_name='authorization',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='tmdb_cover_path',
            new_name='imdb_cover_path',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='latest_version',
            new_name='latestVersion',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='show_streaming',
            new_name='livetv',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='release_note',
            new_name='releaseNotes',
        ),
        migrations.AddField(
            model_name='configuration',
            name='streaming',
            field=models.BooleanField(default=False),
        ),
    ]
