# Generated by Django 3.2.8 on 2021-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_auto_20211031_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='autosubtitles',
            new_name='ad_banner',
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_face_audience_banner',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_face_audience_interstitial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_interstitial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_show_interstitial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_unit_id_banner',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_unit_id_facebook_banner_audience',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_unit_id_facebook_interstitial_audience',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='ad_unit_id_interstitial',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='autosubstitles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='facebook_show_interstitial',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='purchase_key',
            field=models.CharField(blank=True, default='5f107d7d-e117-4858-9dde-8f5eb5839dfd', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tmdb_api_key',
            field=models.CharField(default='9f002d3cbd8d807b5af7339bf13b63fd', max_length=191),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tmdb_lang',
            field=models.JSONField(default={'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}),
        ),
    ]
