# Generated by Django 3.2.8 on 2021-11-04 14:17

import appapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_auto_20211104_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tmdb_lang',
            field=models.JSONField(default=appapi.models.default_tmdb_lang),
        ),
    ]
