# Generated by Django 3.2.8 on 2021-11-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0008_alter_configuration_tmdb_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='splash_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
