# Generated by Django 3.2.8 on 2021-11-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_alter_configuration_splash_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='allow_external_player_to_download',
            new_name='allow_adm',
        ),
    ]
