# Generated by Django 3.2.8 on 2021-11-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0010_rename_allow_external_player_to_download_configuration_allow_adm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='server_choices',
            new_name='server_dialog_selection',
        ),
    ]
