# Generated by Django 3.2.8 on 2021-11-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0012_auto_20211115_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='unity_show',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
