# Generated by Django 3.2.8 on 2021-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0013_alter_configuration_unity_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
