# Generated by Django 3.2.8 on 2021-11-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0014_alter_configuration_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='app_url_android',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='custom_banner_image_link',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='imdb_cover_path',
            field=models.CharField(default='http://image.tmdb.org/t/p/w500', max_length=191),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='splash_image',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
