# Generated by Django 3.2.8 on 2021-11-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0015_auto_20211121_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='app_url_android',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='custom_banner_image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='imdb_cover_path',
            field=models.URLField(default='http://image.tmdb.org/t/p/w500'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='splash_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='telegram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
