from django.urls import path
from . import views,sourceViews
app_name = "app_adminDashboard"
urlpatterns = [
    path("movies/",views.MoviesView.as_view(),name="movies"),
    path("tvs/",views.TVsView.as_view(),name="tvs"),
    path("reports/",views.ReportView.as_view(),name="reports"),
    path("users/",views.UsersView.as_view(),name="users"),
    path("import/tv/",views.ImportTVView.as_view(),name="import_tv"),
    path("import/movie/",views.ImportMovieView.as_view(),name="import_movie"),
    path("import/remote/",views.RemoteImport.as_view(),name="import_remote"),
    path("import/",views.ImportView.as_view(),name="import"),
    path("search/",views.SearchView.as_view(),name="search"),
    path("movie/watchlink/<int:pk>/",views.ShowWatchMovieView.as_view(),name="show_movie_link"),
    path("create/movie/watchlink/<int:pk>/",views.CreateWatchMovieLinkView.as_view(),name="create_movie_link"),
    path("create/episode/watchlink/<int:pk>/",views.CreateWatchEpisodeView.as_view(),name="create_episode_link"),
    path("tv/season/<int:pk>/",views.TVSeasonView.as_view(),name="show_tv_season"),
    path("tv/season/<int:pk>/episodes/",views.TVEpisodeView.as_view(),name="show_season_episode"),
    path("add/tv/season/<int:pk>/",views.AddTVSeasonView.as_view(),name="add_tv_season"),
    path("add/tv/season/<int:pk>/episode",views.AddTVEpisodeView.as_view(),name="add_tv_season_episode"),
    path("episode/watchlink/<int:pk>/",views.ShowWatchEpisodeView.as_view(),name="show_episode_link"),
    path("update/movie/watchlink/<int:pk>/",views.UpdateWatchMovieLinkView.as_view(),name="update_movie_link"),
    path("update/episode/watchlink/<int:pk>/",views.UpdateWatchEpisodeLinkView.as_view(),name="update_episode_link"),
    path("delete/tv/season/episode/<int:pk>/",views.DeleteTVEpisodeView.as_view(),name="delete_tv_episode"),
    path("delete/tv/season/<int:pk>/",views.DeleteTVSeasonView.as_view(),name="delete_tv_season"),
    path("delete/movie/watchlink/<int:pk>/",views.DeleteWatchMovieLinkView.as_view(),name="delete_movie_link"),
    path("delete/episode/watchlink/<int:pk>/",views.DeleteWatchEpisodeView.as_view(),name="delete_episode_link"),
    path("delete/movie/<int:pk>/",views.DeleteMovieView.as_view(),name="delete_movie"),
    path("delete/tv/<int:pk>/",views.DeleteTVView.as_view(),name="delete_tv"),
    path("delete/report/<int:pk>/",views.DeleteReportView.as_view(),name="delete_report"),
    path("delete/user/<int:pk>/",views.DeleteUserView.as_view(),name="delete_user"),
    path("delete/",views.RemoteDelete.as_view(),name="delete_empty"),
    path("addSourceTV/",sourceViews.home),
    path("",views.HomeView.as_view(),name="home"),
]
