# Generated by Django 3.2.8 on 2021-10-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadepisode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='downloadmovie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
