# Generated by Django 3.2.8 on 2021-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_configuration_playdrive_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='gdplayer_password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='gdplayer_username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
