# Generated by Django 3.2.8 on 2021-10-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20211029_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='gdplayer_password',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='gdplayer_username',
        ),
        migrations.AddField(
            model_name='configuration',
            name='gdplayer_auth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
