# Generated by Django 3.2.8 on 2021-10-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_watchepisode_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchepisode',
            options={'verbose_name_plural': 'WatchEpisodes'},
        ),
    ]
