# Generated by Django 3.2.7 on 2021-10-02 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themoviedb_id', models.IntegerField()),
                ('imdb_id', models.IntegerField(blank=True, null=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('original_title', models.CharField(max_length=300)),
                ('overview', models.TextField(null=True)),
                ('backdrop_path', models.URLField(null=True)),
                ('poster_path', models.URLField(null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PP', 'Post Production'), ('R', 'Released')], max_length=25, null=True)),
                ('title', models.CharField(max_length=30)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'movie',
                'ordering': ('-added_on', '-release_date'),
            },
        ),
    ]
