# Generated by Django 3.2.7 on 2021-10-02 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='themoviedb_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('movie', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='watch', related_query_name='has_watch', to='webapp.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('movie', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', related_query_name='has_subtitle', to='webapp.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
