# Generated by Django 3.2.8 on 2021-11-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_report_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-episode_number', '-added_on')},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-season_number', '-added_on')},
        ),
    ]
