# Generated by Django 3.2.8 on 2021-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20211113_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
