# Generated by Django 3.2.7 on 2021-10-02 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_movie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themoviedb_id', models.IntegerField(unique=True)),
                ('imdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('original_title', models.CharField(max_length=300)),
                ('overview', models.TextField(null=True)),
                ('backdrop_path', models.URLField(null=True)),
                ('poster_path', models.URLField(null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tv',
            },
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('tv', models.ManyToManyField(related_name='type', related_query_name='type', to='webapp.TV')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('movie', models.ManyToManyField(db_column='webapp_movie_status', related_name='status', related_query_name='has_status', to='webapp.Movie')),
                ('tv', models.ManyToManyField(db_column='webapp_tv_status', related_name='status', related_query_name='has_status', to='webapp.TV')),
            ],
        ),
    ]
