# Generated by Django 3.2.7 on 2021-10-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20211002_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='movie',
            field=models.ManyToManyField(to='webapp.Movie'),
        ),
        migrations.AlterField(
            model_name='status',
            name='tv',
            field=models.ManyToManyField(to='webapp.TV'),
        ),
    ]
