# Generated by Django 3.2.7 on 2021-10-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20211002_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='tv',
            field=models.ManyToManyField(to='webapp.TV'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(to='webapp.Movie'),
        ),
    ]
