# Generated by Django 3.2.7 on 2021-10-02 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20211002_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'tv_subtitle',
            },
        ),
        migrations.CreateModel(
            name='WatchTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'watch_tv',
            },
        ),
        migrations.RenameModel(
            old_name='Subtitle',
            new_name='MovieSubtitle',
        ),
        migrations.RenameModel(
            old_name='Watch',
            new_name='WatchMovie',
        ),
    ]
