# Generated by Django 3.2.9 on 2022-06-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20220117_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='report',
            name='movie',
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.CharField(max_length=6),
        ),
    ]
