# Generated by Django 3.2.7 on 2021-10-02 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20211002_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_season_id', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('episode_count', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('air_date', models.DateTimeField(blank=True, null=True)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', related_query_name='has_season', to='webapp.tv')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('episode_number', models.IntegerField()),
                ('tmdb_episode_id', models.IntegerField()),
                ('still_path', models.URLField(blank=True, null=True)),
                ('vote_average', models.IntegerField(blank=True, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', related_query_name='has_season', to='webapp.season')),
            ],
        ),
    ]
