# Generated by Django 3.2.9 on 2022-06-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20220613_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='tmdb_episode_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
