# Generated by Django 3.2.7 on 2021-10-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
