# Generated by Django 3.2.9 on 2022-06-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_episode_tmdb_episode_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-added_on',)},
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, null=True, unique=True),
        ),
    ]
