# Generated by Django 3.2.7 on 2021-10-02 08:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_episode_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_subtitle', related_query_name='has_episode_subtitle', to='webapp.episode')),
            ],
            options={
                'db_table': 'episode_subtitle',
            },
        ),
        migrations.CreateModel(
            name='WatchEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=2083)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_episode', related_query_name='has_watch_episode', to='webapp.episode')),
            ],
            options={
                'db_table': 'watch_episode',
            },
        ),
        migrations.DeleteModel(
            name='TVSubtitle',
        ),
        migrations.DeleteModel(
            name='WatchTV',
        ),
    ]
