# Generated by Django 3.2.9 on 2022-08-20 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20220617_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewlog',
            name='viewed_on',
            field=models.DateTimeField(db_column='viewed_on', db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
