# Generated by Django 3.2.7 on 2021-10-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20211002_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchepisode',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchmovie',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
