# Generated by Django 3.2.7 on 2021-10-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20211002_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('-air_date',)},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('-air_date',)},
        ),
        migrations.AddField(
            model_name='episode',
            name='air_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
    ]
