# Generated by Django 3.2.7 on 2021-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20211002_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tmdb_cast_id', models.IntegerField()),
                ('profile_path', models.URLField(blank=True, null=True)),
                ('movie', models.ManyToManyField(to='webapp.Movie')),
                ('tv', models.ManyToManyField(to='webapp.TV')),
            ],
        ),
    ]
