# Generated by Django 3.2.7 on 2021-10-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20211002_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='popularity',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
