# Generated by Django 3.2.7 on 2021-10-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_cast_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
