# Generated by Django 3.2.7 on 2021-10-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20211003_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='episodesubtitle',
            options={'verbose_name_plural': 'EpisodeSubtitles'},
        ),
        migrations.AlterModelOptions(
            name='moviesubtitle',
            options={'verbose_name_plural': 'MovieSubtitles'},
        ),
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name_plural': 'TV Shows'},
        ),
        migrations.AlterModelOptions(
            name='watchepisode',
            options={'verbose_name_plural': 'WatchEpisodes'},
        ),
        migrations.AlterModelOptions(
            name='watchmovie',
            options={'verbose_name_plural': 'WatchMovies'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='original_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='watchepisode',
            name='is_downloadable',
            field=models.BooleanField(default=False, verbose_name='downloadable'),
        ),
        migrations.AlterField(
            model_name='watchmovie',
            name='is_downloadable',
            field=models.BooleanField(default=False, verbose_name='downloadable'),
        ),
        migrations.AlterField(
            model_name='watchmovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', related_query_name='has_watch', to='webapp.movie'),
        ),
    ]
