# Generated by Django 3.2.7 on 2021-10-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20211003_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisplayEpisode',
        ),
        migrations.AddField(
            model_name='cast',
            name='gender',
            field=models.CharField(choices=[(1, 'Female'), (0, 'Male')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='watchmovie',
            name='movie',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='watch', related_query_name='has_watch', to='webapp.movie'),
        ),
    ]
