# Generated by Django 3.2.7 on 2021-10-03 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20211003_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cast',
            options={'ordering': ('popularity',)},
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='p', max_length=10)),
                ('description', models.TextField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('episode', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', related_query_name='has_report', to='webapp.episode')),
                ('movie', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', related_query_name='has_report', to='webapp.movie')),
            ],
        ),
    ]
