# Generated by Django 3.2.7 on 2021-10-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20211003_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('c', 'Cancelled'), ('s', 'Solved')], default='p', max_length=10),
        ),
    ]
