# Generated by Django 3.2.7 on 2021-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20211003_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
