# Generated by Django 3.2.7 on 2021-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('custom_header', models.TextField(blank=True, null=True)),
                ('custom_footer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Configuration',
            },
        ),
    ]
