# Generated by Django 3.2.7 on 2021-10-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='message_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='show_message',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='themoviedb_api_key',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
