# Generated by Django 3.2.7 on 2021-10-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_auto_20211003_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images/favicon'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='movie_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='tv_comment',
            field=models.BooleanField(default=False),
        ),
    ]
