# Generated by Django 3.2.7 on 2021-10-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20211003_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='has_review', to='webapp.movie')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='has_review', to='webapp.tv')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', related_query_name='has_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
    ]
