# Generated by Django 3.2.7 on 2021-10-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
