# Generated by Django 3.2.7 on 2021-10-03 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_remove_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
