# Generated by Django 3.2.7 on 2021-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_review_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
