# Generated by Django 3.2.7 on 2021-10-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20211003_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
