# Generated by Django 3.2.7 on 2021-10-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_auto_20211006_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='vote_average',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=3, null=True),
        ),
    ]
