# Generated by Django 3.2.7 on 2021-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_auto_20211007_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
    ]
