# Generated by Django 3.2.7 on 2021-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0037_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
