# Generated by Django 3.2.7 on 2021-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_auto_20211007_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
