# Generated by Django 3.2.7 on 2021-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_configuration_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
