# Generated by Django 3.2.7 on 2021-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_tv_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='movie',
            field=models.ManyToManyField(null=True, related_name='genre', related_query_name='has_genre', to='webapp.Movie'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='tv',
            field=models.ManyToManyField(null=True, related_name='genre', related_query_name='has_genre', to='webapp.TV'),
        ),
    ]
