# Generated by Django 3.2.7 on 2021-10-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_auto_20211007_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('movie', models.ManyToManyField(related_name='language', related_query_name='has_language', to='webapp.Movie')),
                ('tv', models.ManyToManyField(related_name='language', related_query_name='has_language', to='webapp.TV')),
            ],
        ),
    ]
