# Generated by Django 3.2.7 on 2021-10-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0043_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='original_language',
        ),
    ]
